##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: meaning
  labels:
    app: meaning
spec:
  ports:
  - port: 8084
    name: http
  selector:
    app: meaning
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: meaning-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: meaning
        version: v1
    spec:
      containers:
      - name: meaning
        image: titogarrido/observability-meetup-meaning:1.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8084
